// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_chirps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserChirp = `-- name: CreateUserChirp :one
INSERT INTO user_chirps (created_at, updated_at, body, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateUserChirpParams struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

func (q *Queries) CreateUserChirp(ctx context.Context, arg CreateUserChirpParams) (UserChirp, error) {
	row := q.db.QueryRowContext(ctx, createUserChirp,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Body,
		arg.UserID,
	)
	var i UserChirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
